# Generated by Django 4.2.3 on 2023-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('other_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('passport_number', models.IntegerField(unique=True)),
                ('passport_copy', models.ImageField(upload_to='')),
                ('invitation_letter', models.FileField(upload_to='')),
                ('apt_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_limit', models.IntegerField()),
            ],
        ),
    ]
