# Generated by Django 4.2.3 on 2023-08-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('h_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 11, 13, 49, 205914)),
        ),
        migrations.AddField(
            model_name='appointmentsetting',
            name='apt_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='invitation_letter',
            field=models.FileField(upload_to='.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='passport_copy',
            field=models.ImageField(upload_to='.'),
        ),
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_limit',
            field=models.IntegerField(default=50),
        ),
    ]
