# Generated by Django 4.2.3 on 2023-08-29 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0002_holidays_appointmentsetting_apt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apt_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 16, 19, 36, 475664)),
        ),
    ]
