# Generated by Django 4.2.3 on 2023-08-29 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0003_alter_appointment_apt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 17, 20, 16, 111327)),
        ),
    ]
