# Generated by Django 4.2.3 on 2023-08-29 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0004_alter_appointmentsetting_apt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apt_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 17, 32, 3, 661939)),
        ),
    ]
