# Generated by Django 4.2.3 on 2023-09-01 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0005_alter_appointment_apt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsetting',
            name='apt_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apt_date',
            field=models.DateField(verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='passport_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 15, 24, 15, 809010)),
        ),
    ]
