# Generated by Django 4.2.3 on 2023-09-03 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0008_alter_appointment_invitation_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='invitation_letter',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='passport_copy',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 3, 11, 6, 11, 656224)),
        ),
    ]
