# Generated by Django 4.2.3 on 2023-09-04 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0009_alter_appointment_invitation_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 15, 37, 10, 40231)),
        ),
    ]
