# Generated by Django 4.2.3 on 2023-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0010_alter_appointmentsetting_apt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsetting',
            name='apt_date',
            field=models.DateField(),
        ),
    ]
