# Generated by Django 4.2.3 on 2023-09-07 07:57

import alwaditravel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwaditravel', '0012_alter_appointment_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='invitation_letter',
            field=models.FileField(upload_to='uploads', validators=[alwaditravel.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='passport_copy',
            field=models.ImageField(upload_to='uploads', validators=[alwaditravel.models.validate_file_size]),
        ),
    ]
